# **Libraries**

In [19]:
#import Libraries
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np
import cv2
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
### for models
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

In [11]:
(x_train,y_train),(x_test,y_test) = keras.datasets.cifar10.load_data()

In [15]:
x_train.shape , x_test.shape

((50000, 32, 32, 3), (10000, 32, 32, 3))

# **Data Preprocessing**

In [6]:
#normalization
x_train = x_train/255.0
x_test = x_test/255.0

In [7]:
#sklearn expects ----------
nsamples , nx , ny , nrgb = x_train.shape
x_train2 = x_train.reshape((nsamples,nx*ny*nrgb))

In [12]:
nsamples , nx,ny,nrgb = x_test.shape
x_test2 = x_test.reshape((nsamples,nx*ny*nrgb))

# **Building the models**

### **Random Forest Model**

In [16]:
#initialization
model = RandomForestClassifier()
#fiting model
model.fit(x_train2,y_train)
#predictions
y_pred = model.predict(x_test2)
y_pred

<ipython-input-16-2f51a8383ffb>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(x_train2,y_train)


array([2, 2, 2, ..., 2, 2, 2], dtype=uint8)

In [17]:
#measuring the accuracy
accuracy_score(y_pred,y_test)
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.01      0.16      0.02        49
           1       0.00      0.00      0.00         2
           2       0.99      0.10      0.18      9918
           3       0.00      0.24      0.01        17
           4       0.00      0.00      0.00         0
           5       0.00      0.10      0.00        10
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         2
           8       0.00      0.00      0.00         2
           9       0.00      0.00      0.00         0

    accuracy                           0.10     10000
   macro avg       0.10      0.06      0.02     10000
weighted avg       0.98      0.10      0.18     10000



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### **KNN MODEL**

In [20]:
#initialization
knn = KNeighborsClassifier(n_neighbors= 7)
#fiting model
knn.fit(x_train2,y_train)
#predictions
y_pred_knn = knn.predict(x_test2)
y_pred_knn

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [21]:
#measuring the accuracy
accuracy_score(y_pred_knn,y_test)
print(classification_report(y_pred_knn,y_test))

              precision    recall  f1-score   support

           0       1.00      0.10      0.18      9994
           1       0.00      0.00      0.00         1
           2       0.00      0.25      0.00         4
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         0
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         0

    accuracy                           0.10     10000
   macro avg       0.10      0.04      0.02     10000
weighted avg       1.00      0.10      0.18     10000



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### **Decision Tree Model**

In [22]:
#initialization
dtc = DecisionTreeClassifier()
#fiting model
dtc.fit(x_train2,y_train)
#predictions
y_pred_dtc = dtc.predict(x_test2)
y_pred_dtc

array([0, 5, 0, ..., 0, 0, 0], dtype=uint8)

In [23]:
#measuring the accuracy
accuracy_score(y_pred_dtc,y_test)
print(classification_report(y_pred_dtc,y_test))

              precision    recall  f1-score   support

           0       0.98      0.10      0.18      9807
           1       0.00      0.08      0.00        12
           2       0.00      0.06      0.01        50
           3       0.01      0.16      0.02        56
           4       0.00      0.11      0.00         9
           5       0.00      0.08      0.00        25
           6       0.00      0.00      0.00         2
           7       0.00      0.25      0.00         8
           8       0.00      0.07      0.00        28
           9       0.00      0.00      0.00         3

    accuracy                           0.10     10000
   macro avg       0.10      0.09      0.02     10000
weighted avg       0.96      0.10      0.18     10000



### **Naive Bayes Model**

In [24]:
#initialization
nb = GaussianNB()
#fiting model
nb.fit(x_train2,y_train)
#predictions
y_pred_nb = nb.predict(x_test2)
y_pred_nb

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 1, 1, ..., 1, 1, 1], dtype=uint8)

In [25]:
#measuring the accuracy
accuracy_score(y_pred_nb,y_test)
print(classification_report(y_pred_nb,y_test))

              precision    recall  f1-score   support

           0       0.00      0.04      0.00        26
           1       0.98      0.10      0.18      9794
           2       0.00      0.00      0.00         0
           3       0.03      0.16      0.05       180
           4       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         0
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         0

    accuracy                           0.10     10000
   macro avg       0.10      0.03      0.02     10000
weighted avg       0.96      0.10      0.18     10000



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
